spring:
  application:
    name: resource-server
  aop:
    proxy-target-class: true
server:
  port: 9040
  servlet:
    session:
      cookie:
        name: RESOURCE_SESSIONID

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
