spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8
    username: auth
    password: auth,.
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    type: com.alibaba.druid.pool.DruidDataSource


server:
  port: 9090
  servlet:
    session:
      cookie:
        name: RESOURCE_SESSIONID

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.springcloud.resource.model