spring:
  application:
    name: resource-server
server:
  port: 9040
  servlet:
    session:
      cookie:
        name: RESOURCE_SESSIONID

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

security:
#  oauth2:
#    client:
#      client-id: web_app
#      client-secret: 111111
#      access-token-uri: http://localhost:9030/auth/oauth/token
#      scope: all
    resource:
      user-info-uri: http://localhost:9030/auth/user
      prefer-token-info: false
      id: web_app
      service-id: resource-server