spring:
  application:
    name: zuul
  main:
    allow-bean-definition-overriding: true
server:
  port: 9010
zuul:
  ignored-services: "*"
  routes:
    auth-server:
#      url: "http://localhost:9030"
      path: /auth/**
      serviceId: auth-server
    resource-server:
      path: /resource/**
      serviceId: resource-server
  #url 映射host超时配置生效
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
#serviceId ribbon配置生效
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 10000


