spring:
  application:
    name: zuul
  main:
    allow-bean-definition-overriding: true
server:
  port: 9010
  servlet:
    session:
      cookie:
        name: ZUUL_SESSIONID
zuul:
  ignored-services: "*"
  routes:
    auth-server:
#      url: "http://localhost:9030"
      path: /auth/**
      serviceId: auth-server
    resource-server:
      path: /resource/**
      serviceId: resource-server
  #url 映射host超时配置生效
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  sensitive-headers: Cookie,Set-Cookie
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka

#serviceId ribbon配置生效
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 10000
  eureka:
    enabled: true
#proxy:
#  auth:
#    routes:
#      customers: auth-server
#      stres: test
#      recommendations: none
#security:
#  oauth2:
#    sso:
#      login-path: http://localhost:9030/login
#    client:
#      access-token-uri: http://localhost:9010/auth/oauth/token
#      user-authorization-uri: http://localhost:9010/auth/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:9010/auth/user
