spring:
  application:
    name: zuul

server:
  port: 9010
zuul:
  ignored-services: "*"
  prefix: "/api"
  routes:
    users:
      path: /auth/**
      serviceId: auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

security:
  oauth2:
    client:
      clientId: client
      clientSecret: client-secret
    resource:
      id: resource
      token-info-uri: http://localhost:9020/oauth/check_token
      user-info-uri: http://localhost:9030/resource/user
      prefer-token-info: true
      jwt:
        key-uri: http://localhost:9020/oauth/token_key

